### ISSUE TITLE
Raise errors on all 422's

### ISSUE THREAD

**Issue by bobbytables** [digitalocean/droplet_kit#1]

**Comment by brunomperes** [comment]
I see the commit but it doesn't seem to be raising the errors (and the issue is open). Is is still under development?

**Comment by phillbaker** [comment]
So it looks like #45 only addressed 422s on 2 endpoints, https://github.com/digitalocean/droplet_kit/pull/65 should handle non 20x responses everywhere.

**Comment by phillbaker** [comment]
Closing as #65 is merged.
