### ISSUE TITLE
Images: find by 'private' key

### ISSUE THREAD

**Issue by RocKhalil** [digitalocean/droplet_kit#100]
There should be a boolean key in the find method `private` to list the `private` or `public` images:
https://developers.digitalocean.com/documentation/v2/#list-a-user-s-images

**Comment by phillbaker** [comment]
I believe this is implemented: https://github.com/digitalocean/droplet_kit/blob/master/lib/droplet_kit/resources/image_resource.rb#L7. If you switch to the "ruby" language on the documentation site, you'll see an example of using it.

**Comment by RocKhalil** [comment]
I was trying to implement `.find(private: true)` instead of `.all(private: true)`
