### ISSUE TITLE
Expose Faraday adaptor to allow injecting middleware

### ISSUE THREAD

**Issue by petems** [digitalocean/droplet_kit#102]
Over at Tugboat, we've been using [Barge](https://github.com/blom/barge/) for a while, which has a very similar API to droplet_kit

One of the things we did in Barge was to expose the faraday endpoint:

```ruby
    def faraday
      @faraday ||= Faraday.new faraday_options do |f|
        f.adapter :net_http

        f.request :json

        f.response :follow_redirects
        f.response :mashify
        f.response :json

        f.options.merge! request_options
      end
    end

    private

    def faraday_options
      {
        headers: {
          authorization: "Bearer #{access_token}",
          content_type: 'application/json'
        },
        url: DIGITAL_OCEAN_URL
      }
    end
```

Which allows you to overwrite, including adding your own custom middleware:

```ruby
env['barge'].faraday.use Tugboat::CustomLogger if ENV['DEBUG']
```

This allows us to do things like show debugging logs **with the API key redacted** for users to debug issues:

```bash
I, [2016-10-08T20:53:14.408984 #54987]  INFO -- : Started GET request to: https://api.digitalocean.com/v2/droplets?page=1&per_page=200
D, [2016-10-08T20:53:14.409434 #54987] DEBUG -- : Request Headers:
----------------
Authorization : Bearer [TOKEN REDACTED]
Content-Type  : application/json
User-Agent    : Faraday v0.9.2

Request Body:
-------------
{
  "droplets": [
    {
[etc.]
```

Very cool, and I'm pretty proud of it 👍 

We're looking to possible start using droplet_kit over Barge for Tugboat, would this be something you'd be ok with adding to droplet_kit? 😄

**Comment by phillbaker** [comment]
That sounds great! A PR would be awesome.

**Comment by petems** [comment]
@phillbaker Awesome, PR on the way! 👍
