### ISSUE TITLE
Add homepage link to github on `rubygems.org` page

### ISSUE THREAD

**Issue by ShockwaveNN** [digitalocean/droplet_kit#110]
Hi, it will be much easier to find source code of this gem, if on https://rubygems.org/gems/droplet_kit page will be Homepage link to this github repo.

**Comment by andrewsomething** [comment]
:+1: Good catch. Fixed in #111

**Comment by ShockwaveNN** [comment]
@andrewsomething Ha, I forgot that this data stored in gemspec, not on `rubygems.org` end, so I didn't creat Pull Request by myself :)
