### ISSUE TITLE
Change record TTL ?

### ISSUE THREAD

**Issue by scalp42** [digitalocean/droplet_kit#119]
Hi folks,

Is there a way to change the default TTL for a record through the API ?

Thanks!

**Comment by scalp42** [comment]
I noticed: https://www.digitalocean.com/community/questions/lower-ttl-value-on-dns-records?answer=34000

**Comment by javierav** [comment]
The API docs reflect that is possible to change the TTL (https://developers.digitalocean.com/documentation/v2/#update-a-domain-record) but doesn't work from the current version of this gem 😢

**Comment by andrewsomething** [comment]
Nice catch! Support for this only landed in the API last month, and it looks like we neglected to add it here as well. Fixed in #127, and it will be in the next release.
