### ISSUE TITLE
Creating tags

### ISSUE THREAD

**Issue by kylekyle** [digitalocean/droplet_kit#122]
The 2.0 documentation suggests a tag would be created like this: 

```ruby
client.tags.create(name: 'my_tag')
```

But that gives the error:

```
ArgumentError: {:name=>"my_tag"} does not respond to name, so we can't map it
```

Passing an `OpenStruct` works, but seems like a hack: 

```ruby 
client.tags.create(OpenStruct.new(name: 'my_tag'))
```

**Comment by grampajoe** [comment]
Thanks @kylekyle, you're right, a `DropletKit::Tag` object should be passed instead of a hash. I've opened #123 to update the docs.

**Comment by mauricio** [comment]
And #123 mentions the right way to handle it :)
