### ISSUE TITLE
ssh_keys are not assigned to new droplet

### ISSUE THREAD

**Issue by owen2345** [digitalocean/droplet_kit#128]
Hello,

I tried to create droplets by many ways: droplet_kit, curl, ... trying to assign ssh_keys to new droplet.
I assigned the values manually copying ssh keys from web and getting them by api but none of them works.
My last test:
```
params = {:name=>"domain1", :region=>"nyc1", :image=>"25092162", :size=>"512mb", :ssh_keys=>["99:19:5d:dd:f8:4d:99:0e:c3:41:4a:c4:cf:f3:52:8c", 7493092, 9485273]}
droplet = DropletKit::Droplet.new(params)
created = remote_connection.droplets.create(droplet)
```
and ssh_keys always is null and I can not connect to server to make additional actions (....:@ssh_keys=>nil, :@id=>50204194, ....).

Note: the same results using other libraries and CURL.

Regards,

**Comment by vadim-givola** [comment]
I have the same problem

**Comment by Xosmond** [comment]
For me worked, but I only used fingerprints array

**Comment by philippeboyd** [comment]
Also works for me using the fingerprints

**Comment by hilary** [comment]
Marking this issue closed as it works when using the fingerprints.
