### ISSUE TITLE
How droplet kit fetches pages for all droplets

### ISSUE THREAD

**Issue by petems** [digitalocean/droplet_kit#135]
Hello! I'm currently in the middle of switching Tugboat to use Droplet Kit over Barge.

Most of the code has been a simple switchover, but the pagination of returned nodes is giving me some bother.

Right now I have some code like this to deal with pagination with https://github.com/blom/barge/:

```ruby
      # Get all pages of droplets
      def get_droplet_list(ocean)
        verify_credentials(ocean)

        page = ocean.droplet.all(per_page: 200, page: 1)
        return page.droplets unless page.paginated?

        Enumerator.new do |enum|
          page.droplets.each { |drop| enum.yield drop }
          for page_num in 2..page.last_page
            page = ocean.droplet.all(per_page: 200, page: page_num)
            page.droplets.each { |drop| enum.yield drop }
          end
        end
      end
```

This is so I can fetch 200 at a time, but if there's more than 200 then it can look for the next page, using the paginated? method.

This doesn't seem to be the case for `droplet_kit` and I can't find an example of fetching a large amount of droplets...

So some questions:

* With droplet_kit, how can I make sure I'm fetching all droplets?
* Is `client.droplets.all` enough, or does that default to the API max of 200?

**Comment by andrewsomething** [comment]
Hey @petems! You'll want to take a look at `lib/droplet_kit/paginated_resource.rb`:

https://github.com/digitalocean/droplet_kit/blob/master/lib/droplet_kit/paginated_resource.rb

You'll see that the library handles pagination for you, but that it is using the API default of 20. It does expose the `per_page` argument, so it can be adjusted. You can verify that all Droplets are retrieved by setting it to something small. E.g.:

```ruby
pry(main)> droplets = client.droplets.all(per_page: 1)
pry(main)> droplets.per_page
=> 1
pry(main)> droplets.each.count
=> 13
```

This will take longer as there are more round trips to the API. Setting it to 200, it only requires one call:

```ruby
pry(main)> droplets = client.droplets.all(per_page: 200)
pry(main)> droplets.each.count
=> 13
```

**Comment by petems** [comment]
Awesome, I had mocked out multiple pages in the specs, but looks like it's no longer needed due to the autopagination behaviour 👍 

Thanks @andrewsomething!
