### ISSUE TITLE
Untag resources error

### ISSUE THREAD

**Issue by adamcable** [digitalocean/droplet_kit#136]
I've been using DropletKit for the past year without issues.
Over the past few weeks when I go to run:
tags.untag_resources(name: @tag[0], resources: [{resource_id: droplet_id, resource_type: 'droplet' }])

I see:

error_handling_resourcable.rb:14:in `block (2 levels) in included': 400: {"id":"parameter_missing","message":"param is missing or the value is empty: resources"} (DropletKit::Error)
        from /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.6/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
        from /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.6/lib/resource_kit/action_invoker.rb:19:in `handle_response'
        from /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.6/lib/resource_kit/action_invoker.rb:14:in `call'
        from /root/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/resource_kit-0.1.6/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'

**Comment by mchitten** [comment]
Thanks for the report @adamcable, this should be fixed in version 2.2.2 (just pushed).

**Comment by AdsarAdam** [comment]
Thanks @mchitten - much appreciated!

**Comment by adamcable** [comment]
Thanks @mchitten - much appreciated!
