### ISSUE TITLE
Unable to generate a custom ID while creating a Kubernetes cluster

### ISSUE THREAD

**Issue by febincloudyuga** [digitalocean/droplet_kit#188]
`client.kubernetes_clusters.create(cluster, id: 'cluster_id')`

The expected behaviour here is to create a Kubernetes cluster with an ID `cluster_id`

This does not happen. Instead, a random ID is being assigned to the cluster.

**Comment by andrewsomething** [comment]
Hi @febincloudyuga. Thanks for raising this issue. Unfortunately it looks like the documentation was wrong here. The DigitalOcean API does not support user assigned IDs when creating new resources, Kubernetes clusters included:

https://developers.digitalocean.com/documentation/v2/#create-a-new-kubernetes-cluster

We'll get the docs updated to reflect that. Sorry about the misinformation.
