### ISSUE TITLE
Rails 6 / ActiveSupport 6.0 Support

### ISSUE THREAD

**Issue by kingdonb** [digitalocean/droplet_kit#191]
I think the release of Rails 6 is imminent, can we have this issue tracking what needs to be updated to provide support for the next Rails?

(I just tried starting a new project from rails edge and learned that the ActiveSupport requirement is locked to a version <6, when I forked that and tried to relax the requirement, I got errors perhaps predictably...)

It looks like there is support for Rails 5, so I will back off and use a current supported version for now.  But I'd like to be sure the option to upgrade is there, as soon as the next release is out if possible.  Thanks!

(nb: rails edge is now 6.1 alpha, so it's possible that the breaking changes are actually not in Rails 6)

**Comment by hilary** [comment]
Sounds like a fine plan 😄 

We aren't actively working on Rails 6 support at the moment, however, if you identify changes that need to be made, we can look at incorporating them into our workflow.

**Comment by kingdonb** [comment]
Great.  Well, I can now confirm that my smoke test which failed on Rails edge/master, has passed just fine on Rails 5.2.3 with a stable Ruby version like 2.6.3.  So that'll be all from me for now, I'll be using the stable version, and I can confirm there is an issue upgrading past the rubicon 😆, I will keep the branch open and visit it later on, when I have some work done on my new app.

**Comment by bentranter** [comment]
As we no longer depend on ActiveSupport as of #199, I think it's ok to close this now. `droplet_kit` will work with any version of Rails as there won't be any more ActiveSupport related conflicts.
