### ISSUE TITLE
Managed Databases API?

### ISSUE THREAD

**Issue by excid3** [digitalocean/droplet_kit#205]
Any timeline on when managed databases will be added to the gem?

**Comment by bentranter** [comment]
Hey @excid3, apologies for the delay – I'll bug our managed database team today to see if I can get an answer for you.

**Comment by bentranter** [comment]
Still working on this internally, and again, sorry for the delay. Looking to get a concrete timeline by tomorrow 🤞I'll keep this issue updated.

**Comment by excid3** [comment]
Sounds good. Thanks @bentranter! 👍

**Comment by bentranter** [comment]
Ok @excid3, looks like this is planned to be done before the end of this year. I'm going to try to push to make it happen sooner, but I can't make any guarantees unfortunately.

**Comment by excid3** [comment]
Alright cool! I think that should be fine. 👍

**Comment by bentranter** [comment]
Hey @excid3, small update. Our managed databases team had a super busy quarter, so I took a stab at getting some of the functionality added in https://github.com/digitalocean/droplet_kit/pull/211. With that said, the team has commit to adding the remaining functionality in January. I hope the partial support is enough to get started until then. 🙂

On another slightly disappointing note, we've started our holiday change freeze, so I won't be able to cut a release for the gem with this functionality until January 6, but it will be the first thing I do once the freeze is over.

**Comment by excid3** [comment]
@bentranter Thank you much! This is enough for me to get started. 🤘 

Happy holidays!

**Comment by bentranter** [comment]
@excid3 Glad to read that it was enough for you to get started. 🙂 We've just released [v3.5.0](https://github.com/digitalocean/droplet_kit/releases/tag/v3.5.0) which has full support for managed databases, so I'm going to close this issue.

**Comment by excid3** [comment]
Thanks @bentranter 💯
