### ISSUE TITLE
create_cluster returns nil

### ISSUE THREAD

**Issue by swanny85** [digitalocean/droplet_kit#216]
create_cluster returns nil.  The gem is looking for a 202 response but the server returns 201. I submitted a PR for it #215

**Comment by hilary** [comment]
Your PR is failing at the moment :(

**Comment by swanny85** [comment]
@hilary Yeah, I failed to update the tests.  I updated that last night so everything should be hunky dory.

**Comment by swanny85** [comment]
Fixed as of 3.4.1
