### ISSUE TITLE
No 3.6.0 on rubygems

### ISSUE THREAD

**Issue by ShockwaveNN** [digitalocean/droplet_kit#235]
Latest version on rubygems is 3.5.1:
![image](https://user-images.githubusercontent.com/668524/78359490-d4579600-75bd-11ea-9059-9a7a5d951959.png)

Latest version on github is 3.6.0
https://github.com/digitalocean/droplet_kit/releases

Is that right?

**Comment by bentranter** [comment]
Hey @ShockwaveNN, thanks for bringing this up, and sorry that you ran into this issue. I've pushed the `3.6.0` on RubyGems – https://rubygems.org/gems/droplet_kit/versions/3.6.0.

For a bit of context, we have an internal automation process that pushes the latest Gem version whenever we create GitHub release, but it must have failed for the latest release tag. I'll look into that to make sure it doesn't happen again.

**Comment by ShockwaveNN** [comment]
@bentranter Thank you for quick response )
