### ISSUE TITLE
Allow Faraday v1

### ISSUE THREAD

**Issue by jpalumickas** [digitalocean/droplet_kit#244]
Hello,

A lot of gems now using Faraday v1 and droplet_kit only allows to use Faraday < 1. Is it possible to add support for Faraday v1 to this gem also?

Cheers!

**Comment by bentranter** [comment]
Hey @jpalumickas, thanks for the report. I've opened https://github.com/digitalocean/droplet_kit/pull/245 to try to address this.

**Comment by bentranter** [comment]
As of [v3.8.0](https://github.com/digitalocean/droplet_kit/releases/tag/v3.8.0), any Faraday version greater than v.0.15 can be used with `droplet_kit`.

**Comment by jpalumickas** [comment]
Thank you!
