### ISSUE TITLE
Missing App Platform API implementation

### ISSUE THREAD

**Issue by renehernandez** [digitalocean/droplet_kit#266]
I would like to access the App Platform API using the `droplet_kit` gem instead of the `doctl` cli. 

Are there any plans to do it soon? I can volunteer to work on an initial PR for it, if that would help speed up the development

**Comment by andrewsomething** [comment]
Hi @renehernandez,

It is not actively being worked on at the moment. If you'd like to take a stab at it, please do.

Let us know if you have any questions!
