### ISSUE TITLE
v3.13.0 not showing in RubyGems

### ISSUE THREAD

**Issue by jonnyarnold** [digitalocean/droplet_kit#271]
Hi there! I'm looking to get the latest version of droplet_kit, which shows as [v3.13.0 on Github](https://github.com/digitalocean/droplet_kit/releases), but is only [v3.12.0 on RubyGems](https://rubygems.org/gems/droplet_kit/versions). Is this just a missed push, or am I missing something?

Thanks in advance :)

**Comment by andrewsomething** [comment]
Thanks for flagging this!  Looks like there was a blip in our CD process. It should be available now: https://rubygems.org/gems/droplet_kit/versions/3.13.0
