### ISSUE TITLE
Rubocop integration?

### ISSUE THREAD

**Issue by ShockwaveNN** [digitalocean/droplet_kit#298]
Hi, what authors of this gem thinks about [rubocop](https://github.com/rubocop/rubocop) integration?

I usually ask authors before starting integrating it, since sometimes people are strongly against it.
If it's OK I can make a sample PR with change

**Comment by mikeberezowski** [comment]
Thanks for reaching out. It's a holiday here today so the team is off but we will evaluate this and make a decision next week.

Thanks again for your interest in contributing to DO open source.

**Comment by andrewsomething** [comment]
Hi @ShockwaveNN,

Thanks for the offer to integrate the project with rubocop. I think this would be a great addition. How are you thinking of approaching it, as GitHub Action workflow? 

Unfortunately, running  rubocop against this project shows that we have quite a few "convention" level issues and even a few warnings. So we may need to incrementally enable rules as we clean things up.

**Comment by ShockwaveNN** [comment]
Totally agree about GitHub workflows, it will be the easiest part of the taks

I'll try to make proof of the concept tomorrow, and fix any obvious errors I'll find and we can discuss some other, not so obvious rules after that

**Comment by andrewsomething** [comment]
Closed via #299
