### ISSUE TITLE
Droplet "size" is nil in DropletKit

### ISSUE THREAD

**Issue by ndangles** [digitalocean/droplet_kit#306]
It seems that the `size` definition of a droplet is correctly returned by the API but does not get included in the DropletKit object and is instead set as `nil`

When I manually `curl` the droplet endpoints, i.e. `https://api.digitalocean.com/v2/droplets` or `https://api.digitalocean.com/v2/droplets/SOME_ID` I get the expected response which includes the `size` block like so: 
```
      "size": {
        "slug": "s-1vcpu-1gb",
        "memory": 1024,
        "vcpus": 1,
        "disk": 25,
        "transfer": 1,
        "price_monthly": 6,
        "price_hourly": 0.00893,
        "regions": [
          "ams3",
          "blr1",
          "fra1",
          "lon1",
          "nyc1",
          "nyc3",
          "sfo2",
          "sfo3",
          "sgp1",
          "syd1",
          "tor1"
        ],
        "available": true,
        "description": "Basic"
      },
```

However, when I use `client.droplets.find(id: SOME_ID)` or `client.droplets.all` then `size` is always `nil` like so: `:@size=>nil,`

https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_list
https://docs.digitalocean.com/reference/api/api-reference/#operation/droplets_get

**Comment by ndangles** [comment]
Also, as a side note. It seems the API itself does not return `db_names` when querying for [all clusters](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_list_clusters) or a [single cluster](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_get_cluster). Calling the [database_list](https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_list) endpoint will return the DB names but the response example in the docs for cluster information seems to imply that the DB names will be returned there also

**Comment by ndangles** [comment]
I opened a PR to attempt to address this issue https://github.com/digitalocean/droplet_kit/pull/307

**Comment by andrewsomething** [comment]
Fixed via https://github.com/digitalocean/droplet_kit/pull/307
