### ISSUE TITLE
Add private parameter to image resource

### ISSUE THREAD

**Issue by cao7113** [digitalocean/droplet_kit#31]
To support: "List a user's images"' in API docs, I guess missing ':private' here https://github.com/digitalocean/droplet_kit/blob/master/lib/droplet_kit/resources/image_resource.rb#L5

Make below possible: client.images.all(private: true) for api endpoint:  /v2/images?private=true

**Comment by phillbaker** [comment]
Thanks @cao7113, we'll get this on the roadmap.
