### ISSUE TITLE
Add missing support for Database Cluster Config

### ISSUE THREAD

**Issue by bentranter** [digitalocean/droplet_kit#324]
Add support for two missing database cluster config operations defined here:

  * Get https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_get_config
  * Patch https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_patch_config

There is some existing support for database clusters, so you'll need to extend the implementation for the relevant files in `lib/droplet_kit/mappings`, `lib/droplet_kit/models`, and `lib/droplet_kit/resources`. After that, you'll need to update the documentation for these new methods in the `README.md` file.

To get started, defining operations typically starts with the `resources` file, which for database operations is `lib/resources/database_resource.rb`. You'll add two new actions:

```ruby
action :get_config, 'GET /v2/databases/:id/config' do
  # TODO
end

action :update_config, 'PATCH /v2/databases/:id/config' do
  # TODO
end
```

And implement the body and status code handling from there.

**Comment by caiohsramos** [comment]
@bentranter reading the docs for the `config` object, seems like it can be:
```
Any of
mysql_advanced_config (object) or postgres_advanced_config (object) or redis_advanced_config (object) or mongo_advanced_config (object) or kafka_advanced_config (object) or opensearch_advanced_config (object)
```

Is there a way to represent this with [kartograph](https://github.com/digitalocean/kartograph)? Or just add every possible property to the mapping/model?
