### ISSUE TITLE
Add missing support for updating database connection pools

### ISSUE THREAD

**Issue by bentranter** [digitalocean/droplet_kit#325]
Add support for the missing database cluster connection pool method here:

  * Update https://docs.digitalocean.com/reference/api/api-reference/#operation/databases_update_connectionPool

There is some existing support for database clusters, so you'll need to extend the implementation for the relevant files in `lib/droplet_kit/mappings`, `lib/droplet_kit/models`, and `lib/droplet_kit/resources`. After that, you'll need to update the documentation for these new methods in the `README.md` file.

To get started, defining operations typically starts with the `resources` file, which for database operations is `lib/resources/database_resource.rb`. You'll add one new action:

```ruby
action :update_connection_pool, 'PUT /v2/databases/:id/pools/:name' do
  # TODO
end
```

And implement the body and status code handling from there.

**Comment by caiohsramos** [comment]
@bentranter hey, do you mind if I take a stab at this one? (And the others `hacktoberfest`) issues?
