### ISSUE TITLE
Inconsistent status sometimes after shutdown/boot action (action completed, droplet status not updated immediately)?

### ISSUE THREAD

**Issue by Raekye** [digitalocean/droplet_kit#50]
I've been having this for many months now, but infrequently and hard to reproduce. So say I do a power off. I check the status code is `2xx`. I check that the action status is not "errored". I check that the action status is "completed". But when I check the droplet status, it's "active", not "off"

I'm doing this in a background worker (keep polling action status), and haven't had it for a long time actually so I thought it was fixed, but I just got it again today a few times. By the time I realize it's failed and looked at it, the droplet properly reports "off"

I know it's not a lot of debugging information, but I just wanted to report this issue first and see if anyone has had it/knows anything about it. It's hard to reproduce

Sure, it's not hard to retry a few times checking the droplet status before giving up, but it's messy. When the API reports the event completed successfully, the droplet should be in the proper state.

tl,dr; **power off action completed, droplet status not "off" until a few seconds later**

**Comment by phillbaker** [comment]
@Raekye thanks for opening the issue. Let us dig into this - we'll try to get a working reproduction case and go from there.

**Comment by phillbaker** [comment]
@Raekye can you confirm that you're using API v2 and not v1? If you'd like to email me your DigitalOcean account email at phillip [at] digitalocean.com, that'd help us debug.

**Comment by Raekye** [comment]
Thanks! I am using API v2. I sent you an email

**Comment by phillbaker** [comment]
@Raekye based on a quick look at [the example code you provided](https://github.com/Gamocosm/Gamocosm/blob/master/app/workers/wait_for_stopping_server_worker.rb): 
* Issuing a shutdown event [doesn't guarantee the droplet actually is powered off](https://developers.digitalocean.com/documentation/v2/#shutdown-a-droplet), it guarantees that the signal has been sent to the VM. To guarantee a droplet is off, issue a shutdown, with a reasonable timeout, followed by a `power_off` action.
* The code is not using DropletKit, so this issue isn't related to code in this repo.

Some sample code using DropletKit to show this:
```
client = DropletKit::Client.new(access_token: 'token')
droplet = client.droplets.all.first

# try shutdown - this doesn't guarantee the outcome of Droplet#status
a = client.droplet_actions.shutdown(droplet_id: droplet.id)
until client.actions.find(id: a.id).status == "completed"
  puts client.droplets.find(id: droplet.id).status
end
puts "completed"
puts client.droplets.find(id: droplet.id).status # may still be 'active'

# try power on
a = client.droplet_actions.power_on(droplet_id: droplet.id)
until client.actions.find(id: a.id).status == "completed"
  puts client.droplets.find(id: droplet.id).status
end
puts "completed"
puts client.droplets.find(id: droplet.id).status # will be 'active'

# try power off
a = client.droplet_actions.power_off(droplet_id: droplet.id)
until client.actions.find(id: a.id).status == "completed"
  puts client.droplets.find(id: droplet.id).status
end
puts "completed"
puts client.droplets.find(id: droplet.id).status # will be 'off'
```

**Comment by Raekye** [comment]
Ah thanks, I see. I missed the "A shutdown action is **an attempt**..." I knew that it would try to gracefully stop the server (an attempt) but thought it meant the status would be errored if it could not

Thanks, and sorry for the trouble!
