### ISSUE TITLE
creating a droplet with ssh key?

### ISSUE THREAD

**Issue by Thetoxicarcade** [digitalocean/droplet_kit#51]
The following code gives no errors, it just doesn't create a new droplet...
```
require 'rubygems'
require 'droplet_kit'
token='really_long_secret_token'
client = DropletKit::Client.new(access_token: token)
droplet = DropletKit::Droplet.new(name: 'example', region: 'nyc3', size: '1gb', image: 'ubuntu-14-04-x64', ssh_keys: ["654321", "123456"])
```
I've also specified the keys without quotes.

What's the actual way to do this?

**Comment by phillbaker** [comment]
The third example in [this section](https://github.com/digitalocean/droplet_kit#design) has the line you're missing: `created = client.droplets.create(droplet)`.

`DropletKit::Droplet.new(...)` is just creating an object used to hold the configuration for a Droplet. You have to pass that configuration to the client's Droplet create method.
