### ISSUE TITLE
API documentation error

### ISSUE THREAD

**Issue by brandondrew** [digitalocean/droplet_kit#61]
The API documentation lists this:

```
client.images.all.each(public: false)
```

as the way to get all user images, but that fails with an ArgumentError (bad value for range), so I'm _pretty_ sure it would be something closer to this:

```
client.images.all(public: false).each
```

although that doesn't work either: it gives public images as well.  But that's not a _documentation_ error, so I'll list it separately.

**Comment by phillbaker** [comment]
@brandondrew, sorry for the slow response on this, thanks for pointing this out! 

As you say, it is wrong, but the attribute name is what's wrong. We return public images by default and expose a `private` parameter to conditionally return those images, in this client that happens here: https://github.com/digitalocean/droplet_kit/blob/master/lib/droplet_kit/resources/image_resource.rb#L7. We'll get the docs fixed up shortly.
