### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by brandondrew** [digitalocean/droplet_kit#62]
As mention in #61, the API documentation lists this:
~~~
client.images.all.each(public: false)
~~~
as the way to get all user images.  Since that's not right, I tried this, which seems consistent with code I've seen elsewhere:
~~~
client.images.all(public: false).each
~~~
but that gives public images as well.  It's possible that my correction to the documentation mistake was itself mistaken, but since it *appears* to me to be an error I'll post this in case I'm correct.

In the meantime, this works just fine
~~~
client.images.all.select{|i| i.public == false}.each
~~~

**Comment by phillbaker** [comment]
Updated on #61, this is a documentation error, `client.images.all(private: false)` should work.
