### ISSUE TITLE
keys named other than id_rsa or id_dsa fail.

### ISSUE THREAD

**Issue by gregf** [digitalocean/droplet_kit#66]
I have two keys on digitalocean. One is named ~/.ssh/id_rsa and the other is named ~/.ssh/id_rsa.digitalocean.

If I choose to use the key id for id_rsa test-kitchen will create my server and login using my ssh key.

If I disable id_rsa and choose to use the key named id_rsa.digitalocean it prompts me for a password each time.

**Comment by phillbaker** [comment]
@gregf I skimmed the issue you linked to (https://github.com/test-kitchen/kitchen-digitalocean/issues/43), but I'm not sure how this is a bug in droplet_kit. Does kitchen-digitalocean perhaps rely on key names? A test case that shows a bug in droplet_kit itself would be very helpful if you have one.

**Comment by phillbaker** [comment]
@gregf does test-kitchen need to be configured to use these non-standard keys to ssh to the droplet? For example, to use a key not named id_{rsa,dsa,etc.} you'd have to specify it in the `.ssh/config` or at the command line via something like `ssh -i /path/to/id_foo_bar`.

**Comment by gregf** [comment]
@phillbaker You're right about test-kitchen. A quick grep of the code shows config[:ssh_key]. Thanks for the hint, and sorry to waste your time.
