### ISSUE TITLE
Sudden Issue with API

### ISSUE THREAD

**Issue by hdrsh** [digitalocean/droplet_kit#72]
The api was working perfect till suddenly, around 20 hours hours ago, it started giving me an error.
Even a simple droplet call like:

client = DropletKit::Client.new(access_token: '*token*')
droplets = client.droplets.all
puts droplets

suddenly started giving the following error:

/root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/method_factory.rb:6:in `block in construct': Action 'assign' is already defined on `DropletKit::FloatingIpActionResource` (ArgumentError)
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/method_factory.rb:4:in `construct'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/resource_kit-0.1.4/lib/resource_kit/resource.rb:20:in `resources'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.0/lib/droplet_kit/resources/floating_ip_action_resource.rb:3:in `<class:FloatingIpActionResource>'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.0/lib/droplet_kit/resources/floating_ip_action_resource.rb:2:in `<module:DropletKit>'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.0/lib/droplet_kit/resources/floating_ip_action_resource.rb:1:in `<top (required)>'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.0/lib/droplet_kit/client.rb:33:in `resources'
from /root/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/droplet_kit-1.3.0/lib/droplet_kit/client.rb:38:in `method_missing'
from test.rb

**Comment by hdrsh** [comment]
Figured it out - another gem that was installed and included in the file was causing the trouble.

**Comment by phillbaker** [comment]
Thanks @hdrsh!
