### ISSUE TITLE
Add support for the bock storage API

### ISSUE THREAD

**Issue by supernova32** [digitalocean/droplet_kit#87]
The API is still in private beta, but having it available via DropletKit will really simplify its implementation within the GitHost codebase. We would like to have our implementation ready for when the block storage feature goes out of beta.

I'll see if I can contribute this in some way, but it will take me some time to get acquainted with the codebase.

**Comment by aybabtme** [comment]
hey @supernova32, there's a branch on our Go client that has support for the storage paths, otherwise support in Ruby should come Soon (TM).

See https://github.com/digitalocean/godo/pull/89 if Go is an option for you in the mean time.

**Comment by supernova32** [comment]
@aybabtme thanks for the suggestion! Using the Go API wrapper would require a rewrite of the GitHost app, so it doesn't make much sense to use it, specially since the API endpoint might change in the future.

I'll write a small wrapper lib for the missing functionality, just to test it out and see how we can integrate block storage within GitHost and once the API comes out of beta and is included in DropletKit, I'll switch to it.

**Comment by phillbaker** [comment]
@supernova32 pushed support for the beta endpoints in https://github.com/digitalocean/droplet_kit/pull/89, if you want to pin to a git branch.

**Comment by supernova32** [comment]
Thanks @phillbaker! I'll give that a try 👍
